2024-12-03 21:29:05,326 INFO    MainThread:2965828 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-12-03 21:29:05,329 INFO    MainThread:2965828 [wandb_setup.py:_flush():79] Configure stats pid to 2965828
2024-12-03 21:29:05,330 INFO    MainThread:2965828 [wandb_setup.py:_flush():79] Loading settings from /zhome/2c/2/156505/.config/wandb/settings
2024-12-03 21:29:05,330 INFO    MainThread:2965828 [wandb_setup.py:_flush():79] Loading settings from /work3/s204129/DL2024/02456_RecSys/src_slow/wandb/settings
2024-12-03 21:29:05,330 INFO    MainThread:2965828 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-12-03 21:29:05,331 INFO    MainThread:2965828 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'src_slow/train.py', 'program_abspath': '/work3/s204129/DL2024/02456_RecSys/src_slow/train.py', 'program': '/work3/s204129/DL2024/02456_RecSys/src_slow/train.py'}
2024-12-03 21:29:05,331 INFO    MainThread:2965828 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-03 21:29:05,332 INFO    MainThread:2965828 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-12-03 21:29:05,332 INFO    MainThread:2965828 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-03 21:29:05,333 INFO    MainThread:2965828 [wandb_init.py:_log_setup():533] Logging user logs to /work3/s204129/DL2024/02456_RecSys/src_slow/wandb/run-20241203_212905-eanh1mu4/logs/debug.log
2024-12-03 21:29:05,333 INFO    MainThread:2965828 [wandb_init.py:_log_setup():534] Logging internal logs to /work3/s204129/DL2024/02456_RecSys/src_slow/wandb/run-20241203_212905-eanh1mu4/logs/debug-internal.log
2024-12-03 21:29:05,334 INFO    MainThread:2965828 [wandb_init.py:init():619] calling init triggers
2024-12-03 21:29:05,334 INFO    MainThread:2965828 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'embedding_dim': 300, 'num_heads': 24, 'attention_dim': 64, 'top_N_popular_articles': 5, 'max_history_length': 32, 'popularity_window_hours': 48, 'initial_learning_rate': 0.004894905021654173}
2024-12-03 21:29:05,335 INFO    MainThread:2965828 [wandb_init.py:init():669] starting backend
2024-12-03 21:29:05,335 INFO    MainThread:2965828 [wandb_init.py:init():673] sending inform_init request
2024-12-03 21:29:05,345 INFO    MainThread:2965828 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-03 21:29:05,347 INFO    MainThread:2965828 [wandb_init.py:init():686] backend started and connected
2024-12-03 21:29:05,381 INFO    MainThread:2965828 [wandb_init.py:init():781] updated telemetry
2024-12-03 21:29:05,410 INFO    MainThread:2965828 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-12-03 21:29:05,657 ERROR   MainThread:2965828 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your-wandb-entity not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-03 21:29:05,658 ERROR   MainThread:2965828 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/work3/s204129/DL2024/venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/work3/s204129/DL2024/venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your-wandb-entity not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-03 21:29:05,674 WARNING MsgRouterThr:2965828 [router.py:message_loop():75] message_loop has been closed
